### ISSUE TITLE
Could I run the stmp with multi-sample vcf file?

### ISSUE THREAD

**Issue by hmkim** [AshleyLab/stmp#4]
Hi, there

I ran the analysis using stmp.

but, I can't finish to annotate my variant file (VCF)

This vcf file involve the multi-sample information.

Below is detailed contents in error messsage.

> it into the database. Otherwise this dataset will not be used for annotations.
> 
> Errors:
> 
> 16 warnings and 0 errors in preflight checks.
> +(OK) passed pre-flight checks
> 
> Converting VCF so there is only 1 allele per line
> bcftools split multiallelic command: bcftools norm -m - '/BioTools/stmp/1.3.1/data/test/input_data/merged.vcf' -O z -o '/BioTools/stmp/1.3.1/outputs/scratch/merged_noMultiallelic.vcf.gz'
> bcftools: vcfnorm.c:416: split_info_numeric: Assertion `ret==src->n_allele-1' failed.
> Aborted (core dumped)
> Stripping chr prefix from VCF CHROM column (if present)
> Traceback (most recent call last):
>   File "code/stmp.py", line 437, in <module>
>     main()
>   File "code/stmp.py", line 184, in main
>     stripChr_vcf = stmp_annotation_util.stripChrPrefix(args.vcf, args.scratch_dir, skip_if_exists=True)
>   File "/BioTools/stmp/1.3.1/code/stmp_annotation_util.py", line 164, in stripChrPrefix
>     for line in vcf:
>   File "/usr/lib/python2.7/gzip.py", line 455, in readline
>     c = self.read(readsize)
>   File "/usr/lib/python2.7/gzip.py", line 261, in read
>     self._read(readsize)
>   File "/usr/lib/python2.7/gzip.py", line 308, in _read
>     self._read_eof()
>   File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
>     hex(self.crc)))
> IOError: CRC check failed 0xafdc86bd != 0x6ff95e3L

Thanks in advance!

**Comment by thesyntaxinator** [comment]
It should work with multi-sample VCF files. Which version of bcftools do you have? The error seems to be related to bcftools attempting to split multiallelic variants in your input VCF ("bcftools: vcfnorm.c:416: split_info_numeric: Assertion `ret==src->n_allele-1' failed.").
